[package]
name = "rustuv"
version = "0.0.1"
authors = ["The Rust Project Developers"]
build = "make -C build"

[dependencies.green]
path = "../libgreen"

[dependencies.tls]
git = "https://github.com/alexcrichton/tls-rs"

[[test]]
name = "all"
path = "tests/all.rs"
